### ISSUE TITLE
Make POST requests instead of GET

### ISSUE THREAD

**Issue by Twixes** [timwie/aio-overpass#10]
Great library! Thanks for making it. I've only run into a problem with larger queries: the Overpass server returns code 414 when the GET URL exceeds a few kilobytes. This is not a problem with [POST requests to that same API](https://wiki.openstreetmap.org/wiki/Overpass_API#Quick_Start_.2860_seconds.29:_for_Developers.2FProgrammers), so it would be great to switch to that.

**Comment by timwie** [comment]
Fixed in 0.12.1

**Comment by Twixes** [comment]
Wow, that was fast, thank you!
