### ISSUE TITLE
No geometry in way objects

### ISSUE THREAD

**Issue by bokolob** [timwie/aio-overpass#14]
Hello.
Some way objects don't have geometry field. They have only center, but here - https://github.com/timwie/aio-overpass/blob/b9f44ff70b701d7ee0d66adc356e734f514ce3fa/aio_overpass/element.py#L721
they get None

**Comment by timwie** [comment]
Hey, I'm not sure what issue you are having, can you be more specific?

The function you linked determines what is put into `Way.geometry`, which is `None` when there is no `"geometry"` field.

If there is a `"center"` field, then `Way.center` will be a `Point`; that happens somewhere else in the code

https://github.com/timwie/aio-overpass/blob/b9f44ff70b701d7ee0d66adc356e734f514ce3fa/aio_overpass/element.py#L561

**Comment by bokolob** [comment]
I just get a lot of elements with geometry = None.

It happens with leisure=playground tagged ways almost always, you can try reproduce it.

I can send some examples later.

**Comment by timwie** [comment]
Yeah examples with queries would be great.

Are you sure that you are using `out geom`, and that the playground ways have `"geometry"` fields? Try your queries at http://overpass-turbo.eu and check if the geometry is actually in the result.

**Comment by timwie** [comment]
That's odd, can you paste your query here?

**Comment by bokolob** [comment]
Later today or tomorrow. I'm commuting just now..

**Comment by timwie** [comment]
True, that can be a bit confusing. I will add another issue for this. Thank you!
